services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn sign_language_api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
